Course_Project/Models/PostViewModels/Like.cs
using System;

namespace Course_Project.Models.PostViewModels
{
    public class Like
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();

        public Comment Comment { get; set; }

        public string CommentId { get; set; }

        public ApplicationUser User { get; set; }

        public string UserId { get; set; }
    }
}

Course_Project/Models/PostViewModels/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Course_Project.Models.PostViewModels
{
    public class Post
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();

        public string Category { get; set; }

        [StringLength(100, ErrorMessage = "Maximum {0} characters")]
        public string TagString { get; set; }

        public List<PostTag> PostTags { get; set; } = new List<PostTag>();

        [Required(ErrorMessage = "The Title field is required.")]
        public string Title { get; set; }

        [Display(Name = "Abstract")]
        public string Abstract { get; set; }

        [Required(ErrorMessage = "The Content field is required.")]
        [Display(Name = "Content")]
        public string Content { get; set; }

        public string Comment { get; set; }

        public List<Comment> Comments { get; set; } = new List<Comment>();

        public ApplicationUser Author { get; set; }

        public string AuthorId { get; set; }

        [Display(Name = "Created Date")]
        public DateTime CreatedDate { get; set; }

        public DateTime LastModified { get; set; }

        public List<Raiting> Raitings { get; set; } = new List<Raiting>();
    }
}

Course_Project/Models/PostViewModels/Raiting.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Course_Project.Models.PostViewModels
{
    public class Raiting
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();

        public Post Post { get; set; }

        public string PostId { get; set; }

        public ApplicationUser User { get; set; }

        public string UserId { get; set; }

        [Range(1, 5)]
        public int Value { get; set; }
    }
}

Course_Project/Models/PostViewModels/Tag.cs
using System;
using System.Collections.Generic;

namespace Course_Project.Models.PostViewModels
{
    public class Tag
    {
        public string Id { get; set; } = Guid.NewGuid().ToString();

        public string Name { get; set; }

        public List<PostTag> PostTags { get; set; } = new List<PostTag>();
    }
}

Course_Project/Controllers/PostsController.cs
using Course_Project.Data;
using Course_Project.Models;
using Course_Project.Models.PostViewModels;
using Imgur.API;
using Imgur.API.Authentication.Impl;
using Imgur.API.Endpoints.Impl;
using Imgur.API.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Course_Project.Controllers
{

    public class PostsController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public PostsController(
            IConfiguration configuration,
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _configuration = configuration;
            _context = context;
            _userManager = userManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Posts
                 .Include(a => a.Raitings)
                 .Include(b => b.Comments)
                 .Include(c => c.Author);

            return View(await applicationDbContext.ToListAsync());
        }

        [AllowAnonymous]
        public async Task<IActionResult> Top()
        {
            var applicationDbContext = _context.Posts
                  .Include(a => a.Raitings)
                  .Include(b => b.Comments)
                  .Include(c => c.Author);

            return View(await applicationDbContext.ToListAsync());
        }

        [AllowAnonymous]
        public IActionResult Tag(string tagId)
        {
            ViewData["tagId"] = tagId;
            return View();

        }

        [AllowAnonymous]
        public async Task<IActionResult> DisplaySingleCategory()
        {
            var applicationDbContext = _context.Posts
                  .Include(a => a.Raitings)
                  .Include(b => b.Comments)
                  .Include(c => c.Author);

            return View(await applicationDbContext.ToListAsync());
        }

        [Authorize(Roles = "Admin,Author")]
        public IActionResult Create(string id)
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Author")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("AuthorId, Title, Abstract,Content,Category,TagString")]
            Post post,
            string id)
        {
            if (ModelState.IsValid)
            {
                SetTags(post);
                post.LastModified = DateTime.UtcNow;
                if (await IsRightsForChangeAsync(id))
                {
                    post.Author = await _userManager.FindByIdAsync(id);
                }
                else
                {
                    post.Author = await _userManager.GetUserAsync(User);
                }
                post.CreatedDate = DateTime.UtcNow;
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var post = await _context.Posts
                .Include(a => a.Author)
                .Include(c => c.Comments)
                .Include(a => a.Raitings)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddComment(string postId, Post post)
        {
            var user = await _userManager.GetUserAsync(User);
            var commentedPost = await _context.Posts
                .Include(a => a.Author)
                .Include(a => a.Raitings)
                .Include(c => c.Comments)
                .SingleOrDefaultAsync(m => m.Id == postId);
            if (post.Comment.Length > 300)
            {
                return PartialView("_CommentsBody", commentedPost);
            }

            _context.Comments.Add(new Comment()
            {
                Text = post.Comment,
                CreatedDate = DateTime.UtcNow,
                Author = user,
                PostId = commentedPost.Id,
                Post = commentedPost
            });
            _context.SaveChanges();
            return PartialView("_CommentsBody", commentedPost);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddLike(string Id)
        {
            var comment = _context.Comments
                .Where(a => a.Id == Id)
                .Include(a => a.Author)
                .Include(a => a.Likes)
                .SingleOrDefault();
            var user = await _userManager.GetUserAsync(User);
            var isLiked = _context.Likes
                .Where(n => n.CommentId == comment.Id && n.UserId == user.Id)
                .SingleOrDefault();
            if (isLiked == null)
            {
                Like newLike = new Like()
                {
                    UserId = user.Id,
                    Comment = comment,
                    CommentId = comment.Id
                };

                _context.Likes.Add(newLike);
            }
            else
            {
                _context.Likes.Remove(isLiked);
            }
            _context.SaveChanges();
            return PartialView("_Like", comment);
        }


        [Authorize(Roles = "Admin,Author")]
        public async Task<IActionResult> UploadImageAsync(IFormFile file)
        {
            IImage image = null;
            try
            {
                var client = new ImgurClient(
                                _configuration["Authentication:Imgur:ClientId"],
                                _configuration["Authentication:Imgur:ClientSecret"]);
                var endpoint = new ImageEndpoint(client);
                if (file.Length > 0)
                {
                    using (var fileStream = file.OpenReadStream())
                    using (var ms = new MemoryStream())
                    {
                        fileStream.CopyTo(ms);
                        var fileBytes = ms.ToArray();
                        string s = Convert.ToBase64String(fileBytes);
                        image = await endpoint.UploadImageBinaryAsync(fileBytes);
                    }
                }
            }
            catch (ImgurException imgurEx)
            {
                Debug.Write("An error occurred uploading an image to Imgur.");
                Debug.Write(imgurEx.Message);
            }
            return Json(new { location = image.Link });
        }

        [Authorize(Roles = "Admin,Author")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Posts.SingleOrDefaultAsync(m => m.Id == id);
            var userId = article.AuthorId;
            if (!await IsRightsForChangeAsync(userId))
            {
                return RedirectToAction("AccessDenied", "Account");
            }
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        [HttpPost]
        [Authorize(Roles = "Admin,Author")]
        public async Task<IActionResult> Edit(Post post)
        {
            var parentPost = await _context.Posts.SingleOrDefaultAsync(m => m.Id == post.Id);
            var userId = parentPost.AuthorId;
            if (!await IsRightsForChangeAsync(userId))
            {
                return RedirectToAction("AccessDenied", "Account");
            }
            SetTags(post);
            RemoveOldTagsAsync(post);
            parentPost.Content = post.Content;
            parentPost.Category = post.Category;
            parentPost.Abstract = post.Abstract;
            parentPost.TagString = post.TagString;
            parentPost.Title = post.Title;
            parentPost.LastModified = DateTime.UtcNow;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin,Author")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var article = await _context.Posts.SingleOrDefaultAsync(m => m.Id == id);
            var userId = article.AuthorId;
            if (!await IsRightsForChangeAsync(userId))
            {
                return RedirectToAction("AccessDenied", "Account");
            }
            if (article == null)
            {
                return NotFound();
            }
            return View(article);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin,Author")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var article = await _context.Posts.SingleOrDefaultAsync(m => m.Id == id);
            var userId = article.AuthorId;
            if (!await IsRightsForChangeAsync(userId))
            {
                return RedirectToAction("AccessDenied", "Account");
            }
            _context.Posts.Remove(article);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize]

Course_Project/ViewComponents/LatestPostsViewComponent.cs
using Course_Project.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Course_Project.ViewComponents
{
    public class LatestPostsViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public LatestPostsViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int howMany)
        {

            var lastPost = await _context.Posts
                                            .OrderByDescending(a => a.LastModified)
                                            .Include(a => a.Author)
                                            .Include(a => a.Raitings)
                                            .Include(b => b.Comments)
                                            .Take(howMany)
                                            .ToListAsync();
            return View(lastPost);
        }
    }
}

Course_Project/ViewComponents/PostByTagViewComponent.cs
using Course_Project.Data;
using Course_Project.Models.PostViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace Course_Project.ViewComponents
{
    public class PostByTagViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public PostByTagViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int howMany, string tagId)
        {
            var postWithCurrentTag = new List<Post>();
            var postTags = await _context.PostTags.Where(t => t.TagId == tagId).ToListAsync();
            foreach (var postTag in postTags)
            {
                postWithCurrentTag.Add(_context.Posts
                                                .Include(a => a.Raitings)
                                                .Include(b => b.Comments)
                                                .Include(c => c.Author)
                                                .SingleOrDefault(m => m.Id == postTag.PostId));
            }
            return View(postWithCurrentTag);
        }
    }
}

Course_Project/ViewComponents/TopPostsViewComponent.cs
using Course_Project.Data;
using Course_Project.Models.PostViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Course_Project.ViewComponents
{
    public class TopPostsViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        public TopPostsViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int howMany)
        {
            var sortedPosts = new Dictionary<Post, double>();
            var posts = await _context.Posts
                 .Include(a => a.Author)
                 .Include(a => a.Raitings)
                 .Include(b => b.Comments)
                 .ToListAsync();

            foreach (var post in posts)
            {
                double raiting = 0.0;
                try
                {
                    raiting = await _context.Raitings
                    .Include(a => a.Post)
                    .Where(p => p.Post.Id == post.Id)
                    .Select(v => v.Value)
                    .AverageAsync();
                }
                catch
                {
                    raiting = 0.0;
                }
                finally
                {
                    sortedPosts.Add(post, raiting);
                    sortedPosts = sortedPosts
                        .OrderByDescending(x => x.Value)
                        .ToDictionary(x => x.Key, x => x.Value);
                }
            }
            return View(sortedPosts);
        }
    }
}

Course_Project/Views/Posts/Create.cshtml
@model Course_Project.Models.PostViewModels.Post
@{
    ViewData["Title"] = Localizer["Create post"];
}

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>@Localizer["Create post"]</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label">@Localizer["Title"]</label>
            <div class="col-md-6">
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger" />
            </div>
            <label asp-for="Category" class="col-md-2 control-label">@Localizer["Category"]</label>
            <div class="btn-group">
                <select id="categorySelect" asp-for="Category"
                        asp-items="@new SelectList(context.Categories.Select(c => c.CategoryName))"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TagString" class="col-md-2 control-label">@Localizer["TagString"]</label>
            <div class="col-md-10">
                <input asp-for="TagString" class="form-control" data-role="tagsinput"
                       placeholder="@Localizer["One tag up to 25 characters, maximum 100 characters"]" />
                <span asp-validation-for="TagString" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Abstract" class="col-md-2 control-label">@Localizer["Abstract"]</label>
            <div class="col-md-10">
                <textarea asp-for="Abstract" class="form-control" rows="7" required></textarea>
                <span asp-validation-for="Abstract" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="col-md-2 control-label">@Localizer["Content"]</label>
            <div class="col-md-10">
                <textarea asp-for="Content" class="form-control" rows="28" required></textarea>
                <span asp-validation-for="Content" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@Localizer["Create post"] class="btn btn-default" />
            </div>
        </div>
    </div>
</form>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
                tinymce.init({
            selector: 'textarea',
            language: "@CultureInfo.CurrentCulture.Name",
            plugins: 'image code',
            toolbar: 'undo redo | image code',
            images_upload_url: '/Posts/UploadImageAsync'
        });
    </script>
}

Course_Project/Views/Posts/Delete.cshtml
@model Course_Project.Models.PostViewModels.Post
@{
    ViewData["Title"] = Localizer["Delete post"];
}
<h2>@Localizer["Delete post"]</h2>
<h3>@Localizer["Are you sure you want to delete this?"]</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Abstract)
        </dt>
        <dd>
            @Html.Raw(Model.Abstract)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd>
            @Html.Raw(Model.Content)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value=@Localizer["Delete post"] class="btn btn-default" /> |
            <a asp-action="Index">@Localizer["Back to List"]</a>
        </div>
    </form>
</div>

Course_Project/Views/Posts/Details.cshtml
@model Course_Project.Models.PostViewModels.Post
@{
    ViewData["Title"] = Model.Title;
}
<br />
<br />
<div class="article-page container" id="allUp">
    <div class="col-md-12 article-details">
        @Html.Partial("_PostSummary", Model)
        @Html.Raw(Model.Content)
    </div>
    <div class="col-md-12 article-details">
        @Html.Partial("_CommentsBody", Model)
        @Html.Partial("_NewComment", Model)
    </div>
</div>

Course_Project/Views/Posts/DisplaySingleCategory.cshtml
@model IEnumerable<Course_Project.Models.PostViewModels.Post>
@{
    ViewData["Title"] = Context.Request.Query["category"];
}
<div class="container">
    <ul class="col-md-12 list-unstyled article-list">
        <li class="row">
            @await Component.InvokeAsync(
                     "CategoryPosts",
                     new { category = Context.Request.Query["category"].ToString(), howMany = 10 })
        </li>
    </ul>
</div>

Course_Project/Views/Posts/Edit.cshtml
@model Course_Project.Models.PostViewModels.Post
@{
    ViewData["Title"] = Localizer["Edit post"];
}

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>@Localizer["Edit post"]</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Title" class="col-md-2 control-label">@Localizer["Title"]</label>
            <div class="col-md-6">
                <input asp-for="Title" value="@Model.Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger" />
            </div>
            <label asp-for="Category" class="col-md-2 control-label">@Localizer["Category"]</label>
            <div class="btn-group">
                <select id="categorySelect" asp-for="Category"
                        asp-items="@new SelectList(context.Categories.Select(c => c.CategoryName))"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TagString" class="col-md-2 control-label">@Localizer["TagString"]</label>
            <div class="col-md-10">
                <input asp-for="TagString" value="@Model.TagString" class="form-control" data-role="tagsinput"
                       placeholder="@Localizer["One tag up to 25 characters, maximum 100 characters"]" />
                <span asp-validation-for="TagString" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Abstract" class="col-md-2 control-label">@Localizer["Abstract"]</label>
            <div class="col-md-10">
                <textarea asp-for="Abstract" class="form-control" rows="7" required>
                    {@Model.Abstract}
                </textarea>
                <span asp-validation-for="Abstract" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="col-md-2 control-label">@Localizer["Content"]</label>
            <div class="col-md-10">
                <textarea asp-for="Content" class="form-control" rows="28">
                    {@Model.Content}
                </textarea>
                <span asp-validation-for="Content" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
            </div>
        </div>
        <input type="submit" value=@Localizer["Edit post"] class="btn btn-default" />
    </div>
</form>
<div>
    <a asp-action="Index">@Localizer["Back to List"]</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        tinymce.init({
            selector: 'textarea',
            language: "@CultureInfo.CurrentCulture.Name",
            plugins: 'image code',
            toolbar: 'undo redo | image code',
            images_upload_url: '/Posts/UploadImageAsync'
        });
    </script>
}

Course_Project/Views/Posts/Index.cshtml
@model IEnumerable<Course_Project.Models.PostViewModels.Post>
@{
    ViewData["Title"] = @Localizer["News"];
}

<div class="row">
    <div class="col-md-9">
        <ul class="list-unstyled article-list">
            <li class="row">
                @await Component.InvokeAsync("LatestPosts", new { howMany = 15 })
            </li>
        </ul>
    </div>
    @Html.Partial("_TagCloud")
</div>

Course_Project/Views/Posts/Tag.cshtml
@{
    ViewData["Title"] = @Localizer["News"];
}

<div class="row">
    <div class="col-md-9">
        <ul class="list-unstyled article-list">
            <li class="row">
                @await Component.InvokeAsync("PostByTag", new { howMany = 15, tagId = ViewData["tagId"] })
            </li>
        </ul>
    </div>
    @Html.Partial("_TagCloud")
</div>

Course_Project/Views/Posts/Top.cshtml
@model IEnumerable<Course_Project.Models.PostViewModels.Post>
@{
    ViewData["Title"] = @Localizer["Top news"];
}
<div class="row">
    <div class="col-md-9">
        <ul class="col-md-12 list-unstyled article-list">
            <li class="row">
                @await Component.InvokeAsync("TopPosts", new { howMany = 15 })
            </li>
        </ul>
    </div>
    @Html.Partial("_TagCloud")
</div>

Course_Project/Views/Posts/_CommentsBody.cshtml
@model Course_Project.Models.PostViewModels.Post

<section id="comments">
    <div class="container" id="commentsContainer">
        <h2>@Localizer["Comments:"]</h2>
        @foreach (var comment in context.Comments)
        {
            if (comment.PostId == Model.Id && Model.Comments.SingleOrDefault(m => m.Id == comment.Id) == null)
            {
                Model.Comments.Add(comment);
            }
        }
        @if (Model.Comments.Count == 0)
        {
            <p>@Localizer["There are no comments for this news"]</p>
        }
        else
        {
            @foreach (var comment in Model.Comments.OrderBy(a => a.CreatedDate))
            {
                var author = await UserManager.FindByIdAsync(comment.AuthorId);
                int CountsOfLike = 0;
                var UserComments = context.Comments.Where(n => n.AuthorId == comment.AuthorId);
                foreach (var comm in UserComments)
                {
                    var Likes = context.Likes.Where(n => n.CommentId == comm.Id);
                    CountsOfLike += Likes.Count();
                }
                <div class="comments-container">
                    <ul id="comments-list" class="comments-list">
                        <li>
                            <div class="comment-main-level">
                                <div class="comment-avatar">
                                    <img src=@author.ProfilePicture alt="UseLogo">
                                </div>
                                <div class="comment-box">
                                    <div id="commentHead" class="comment-head">
                                        <h6 class="comment-name">
                                            <a asp-controller="Profile" asp-action="Index" asp-route-id="@author.Id">
                                                @Html.Raw(author)
                                            </a>
                                            <i class="fa fa-heart" style="color:dodgerblue;top:-1px">
                                                @CountsOfLike
                                            </i>
                                        </h6>
                                        <span style="margin-right: 10px;">@Html.Raw(comment.CreatedDate)</span>
                                        @Html.Partial("_Like", comment)
                                    </div>
                                    <div class="comment-content">
                                        @comment.Text
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            }
        }
    </div>
</section>

Course_Project/Views/Posts/_Like.cshtml
@model Course_Project.Models.PostViewModels.Comment
@{
    var CountOfLikes = context.Likes.Where(n => n.CommentId == Model.Id).Count();
}

@if (SignInManager.IsSignedIn(User))
{
    var user = await UserManager.GetUserAsync(User);
    var isLiked = context.Likes.Where(n => n.CommentId == Model.Id && n.UserId == user.Id).SingleOrDefault();
    <form id="@Model.Id" asp-action="AddLike" asp-route-Id="@Model.Id" data-ajax="true"
          data-ajax-method="POST" data-ajax-success="onSuccessLike">
        @if (isLiked == null)
        {
            <button class="ghost-button" type="submit" form="@Model.Id">
                <i id="heart" class="fa fa-heart"></i>
            </button>
            <i id="countOfLikes">@CountOfLikes</i>
        }
        else
        {
            <button class="ghost-button" type="submit" form="@Model.Id">
                <i id="heart" class="fa fa-heart" style="color:red"></i>
            </button>
            <i id="countOfLikes" style="color:red">@CountOfLikes</i>
        }
    </form>
}
else
{
    <i id="heart" class="fa fa-heart"></i>
    <i id="countOfLikes">@CountOfLikes</i>
}

Course_Project/Views/Posts/_TagCloud.cshtml
@{
    var tags = context.PostTags.ToList();
    Dictionary<string, int> map = new Dictionary<string, int>();
}

<aside class="col-md-3" id="tagCloud" style="text-align:center;">
    <h1>@Localizer["Tag cloud"]</h1>
    <ul class="tag-cloud">
        @foreach (var t in tags)
        {
            var tag = context.Tags.SingleOrDefault(m => m.Id == t.TagId);
            if (map.ContainsKey(tag.Name))
            {
                var value = map.GetValueOrDefault(tag.Name);
                map.Remove(tag.Name);
                map.Add(tag.Name, value + 1);
            }
            else
            {
                map.Add(tag.Name, 1);

            }
        }

        @foreach (KeyValuePair<string, int> c in map)
        {
            var size = (c.Value > 10) ? "w10" : "w" + c.Value;
            var tag = context.Tags.SingleOrDefault(n => n.Name == c.Key);
            <li><a asp-controller="Posts" asp-action="Tag" asp-route-tagId=@tag.Id class=@size>@tag.Name</a></li>
        }
    </ul>
</aside>